sudo: required
#
services:
  - docker
env:
  global:
    - REGISTRY_USER=zhanghongqi

before_install:
  - sudo apt-get update
  - docker ps
  - uname -a
    #- ./docker-ins.sh

before_script:
  - docker pull wavecloud/cowspeak || true
script:
  - docker build --pull --cache-from wavecloud/cowspeak --tag wavecloud/cowspeak .
  - docker run wavecloud/cowspeak

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push wavecloud/cowspeak
  on:
    branch: master
